[env:esp32-s3-devkitc-1]
platform = espressif32@^6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Variante N16R8 : 16 Mo Flash QIO + 8 Mo PSRAM octale.
; La PSRAM octale occupe les GPIO 33-37, à ne jamais utiliser.
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_deps =
    tzapu/WiFiManager@^2.0.17
    teemuatlut/TMCStepper@^0.7.3

monitor_filters = esp32_exception_decoder
